"""create financial schema

Creates the full relational model (currencies, rates, receivable types,
assignors, batches, receivables, settlements) and seeds the reference data
required for the engine to operate: BRL/USD currencies and the receivable
types with the risk spreads defined by the business (Duplicata 1.5% p.m.,
Cheque 2.5% p.m.).

Revision ID: cf5cd043f352
Revises:
Create Date: 2026-07-07 15:17:58.418803

"""

from collections.abc import Sequence
from decimal import Decimal

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf5cd043f352"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assignors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("document", sa.String(length=14), nullable=False, comment="CNPJ (digits only)"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(document) = 14", name=op.f("ck_assignors_document_length")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignors")),
        sa.UniqueConstraint("document", name=op.f("uq_assignors_document")),
    )
    op.create_table(
        "currencies",
        sa.Column("code", sa.String(length=3), nullable=False, comment="ISO 4217 code"),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "decimal_places",
            sa.SmallInteger(),
            nullable=False,
            comment="Rounding precision for monetary amounts",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_currencies")),
    )
    op.create_table(
        "receivable_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False, comment="DUPLICATA, CHEQUE, ..."),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "monthly_spread",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
            comment="Risk spread per month as a decimal fraction (0.015 = 1.5% p.m.)",
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "monthly_spread >= 0", name=op.f("ck_receivable_types_monthly_spread_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receivable_types")),
        sa.UniqueConstraint("code", name=op.f("uq_receivable_types_code")),
    )
    op.create_table(
        "base_rates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column(
            "monthly_rate",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
            comment="Monthly base rate as a decimal fraction (0.01 = 1% p.m.)",
        ),
        sa.Column(
            "effective_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Moment from which this rate is valid",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "monthly_rate >= 0", name=op.f("ck_base_rates_monthly_rate_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["currency_code"],
            ["currencies.code"],
            name=op.f("fk_base_rates_currency_code_currencies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_base_rates")),
        sa.UniqueConstraint(
            "currency_code", "effective_at", name=op.f("uq_base_rates_currency_code")
        ),
    )
    op.create_index(
        "ix_base_rates_currency_effective",
        "base_rates",
        ["currency_code", "effective_at"],
        unique=False,
    )
    op.create_table(
        "batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assignor_id", sa.Uuid(), nullable=False),
        sa.Column("payment_currency_code", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, comment="Optimistic locking token"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'SETTLED')", name=op.f("ck_batches_status_valid")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_batches_version_positive")),
        sa.ForeignKeyConstraint(
            ["assignor_id"], ["assignors.id"], name=op.f("fk_batches_assignor_id_assignors")
        ),
        sa.ForeignKeyConstraint(
            ["payment_currency_code"],
            ["currencies.code"],
            name=op.f("fk_batches_payment_currency_code_currencies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batches")),
    )
    op.create_index(op.f("ix_batches_assignor_id"), "batches", ["assignor_id"], unique=False)
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("base_currency_code", sa.String(length=3), nullable=False),
        sa.Column("quote_currency_code", sa.String(length=3), nullable=False),
        sa.Column(
            "rate",
            sa.Numeric(precision=20, scale=10),
            nullable=False,
            comment="Units of quote currency per 1 unit of base currency",
        ),
        sa.Column(
            "source", sa.String(length=30), nullable=False, comment="MANUAL or MOCK_PROVIDER"
        ),
        sa.Column(
            "effective_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Moment from which this rate is valid",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_currency_code <> quote_currency_code",
            name=op.f("ck_exchange_rates_distinct_currencies"),
        ),
        sa.CheckConstraint("rate > 0", name=op.f("ck_exchange_rates_rate_positive")),
        sa.ForeignKeyConstraint(
            ["base_currency_code"],
            ["currencies.code"],
            name=op.f("fk_exchange_rates_base_currency_code_currencies"),
        ),
        sa.ForeignKeyConstraint(
            ["quote_currency_code"],
            ["currencies.code"],
            name=op.f("fk_exchange_rates_quote_currency_code_currencies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchange_rates")),
        sa.UniqueConstraint(
            "base_currency_code",
            "quote_currency_code",
            "effective_at",
            name=op.f("uq_exchange_rates_base_currency_code"),
        ),
    )
    op.create_index(
        "ix_exchange_rates_pair_effective",
        "exchange_rates",
        ["base_currency_code", "quote_currency_code", "effective_at"],
        unique=False,
    )
    op.create_table(
        "receivables",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("receivable_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "face_value",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
            comment="Face value in the receivable currency",
        ),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("face_value > 0", name=op.f("ck_receivables_face_value_positive")),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["batches.id"], name=op.f("fk_receivables_batch_id_batches")
        ),
        sa.ForeignKeyConstraint(
            ["currency_code"],
            ["currencies.code"],
            name=op.f("fk_receivables_currency_code_currencies"),
        ),
        sa.ForeignKeyConstraint(
            ["receivable_type_id"],
            ["receivable_types.id"],
            name=op.f("fk_receivables_receivable_type_id_receivable_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receivables")),
    )
    op.create_index(op.f("ix_receivables_batch_id"), "receivables", ["batch_id"], unique=False)
    op.create_table(
        "settlements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("payment_currency_code", sa.String(length=3), nullable=False),
        sa.Column(
            "fx_rate",
            sa.Numeric(precision=20, scale=10),
            nullable=True,
            comment="FX rate applied for cross-currency batches (null when same currency)",
        ),
        sa.Column(
            "fx_rate_id", sa.Uuid(), nullable=True, comment="Provenance of the applied FX rate"
        ),
        sa.Column(
            "total_face_value",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
            comment="Sum of face values, in payment currency",
        ),
        sa.Column(
            "total_present_value",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
            comment="Sum of present values, in payment currency",
        ),
        sa.Column(
            "total_discount",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
            comment="Total desagio (face - present), in payment currency",
        ),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "total_discount >= 0", name=op.f("ck_settlements_total_discount_non_negative")
        ),
        sa.CheckConstraint(
            "total_present_value >= 0", name=op.f("ck_settlements_total_present_value_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["batches.id"], name=op.f("fk_settlements_batch_id_batches")
        ),
        sa.ForeignKeyConstraint(
            ["fx_rate_id"],
            ["exchange_rates.id"],
            name=op.f("fk_settlements_fx_rate_id_exchange_rates"),
        ),
        sa.ForeignKeyConstraint(
            ["payment_currency_code"],
            ["currencies.code"],
            name=op.f("fk_settlements_payment_currency_code_currencies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlements")),
        sa.UniqueConstraint("batch_id", name=op.f("uq_settlements_batch_id")),
    )
    op.create_table(
        "settlement_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("settlement_id", sa.Uuid(), nullable=False),
        sa.Column("receivable_id", sa.Uuid(), nullable=False),
        sa.Column(
            "face_value",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
            comment="Face value in the receivable currency",
        ),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column(
            "base_rate_monthly",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
            comment="Base rate snapshot used in the formula",
        ),
        sa.Column(
            "spread_monthly",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
            comment="Risk spread snapshot used in the formula",
        ),
        sa.Column(
            "term_months",
            sa.Numeric(precision=10, scale=4),
            nullable=False,
            comment="Term in months (calendar days / 30)",
        ),
        sa.Column(
            "present_value",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
            comment="Present value in the receivable currency",
        ),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
            comment="Desagio in the receivable currency (face - present)",
        ),
        sa.Column(
            "fx_rate",
            sa.Numeric(precision=20, scale=10),
            nullable=True,
            comment="FX rate applied to this item (null when same currency)",
        ),
        sa.Column(
            "present_value_payment",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
            comment="Present value converted to the batch payment currency",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["currency_code"],
            ["currencies.code"],
            name=op.f("fk_settlement_items_currency_code_currencies"),
        ),
        sa.ForeignKeyConstraint(
            ["receivable_id"],
            ["receivables.id"],
            name=op.f("fk_settlement_items_receivable_id_receivables"),
        ),
        sa.ForeignKeyConstraint(
            ["settlement_id"],
            ["settlements.id"],
            name=op.f("fk_settlement_items_settlement_id_settlements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlement_items")),
        sa.UniqueConstraint("receivable_id", name=op.f("uq_settlement_items_receivable_id")),
    )
    op.create_index(
        op.f("ix_settlement_items_settlement_id"),
        "settlement_items",
        ["settlement_id"],
        unique=False,
    )

    _seed_reference_data()


def _seed_reference_data() -> None:
    """Reference data without which the engine cannot price anything."""
    currencies = sa.table(
        "currencies",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("decimal_places", sa.SmallInteger),
    )
    op.bulk_insert(
        currencies,
        [
            {"code": "BRL", "name": "Brazilian Real", "decimal_places": 2},
            {"code": "USD", "name": "US Dollar", "decimal_places": 2},
        ],
    )

    receivable_types = sa.table(
        "receivable_types",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("monthly_spread", sa.Numeric),
        sa.column("active", sa.Boolean),
    )
    op.bulk_insert(
        receivable_types,
        [
            {
                "code": "DUPLICATA",
                "name": "Duplicata Mercantil",
                "monthly_spread": Decimal("0.015"),
                "active": True,
            },
            {
                "code": "CHEQUE",
                "name": "Cheque Pré-datado",
                "monthly_spread": Decimal("0.025"),
                "active": True,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_settlement_items_settlement_id"), table_name="settlement_items")
    op.drop_table("settlement_items")
    op.drop_table("settlements")
    op.drop_index(op.f("ix_receivables_batch_id"), table_name="receivables")
    op.drop_table("receivables")
    op.drop_index("ix_exchange_rates_pair_effective", table_name="exchange_rates")
    op.drop_table("exchange_rates")
    op.drop_index(op.f("ix_batches_assignor_id"), table_name="batches")
    op.drop_table("batches")
    op.drop_index("ix_base_rates_currency_effective", table_name="base_rates")
    op.drop_table("base_rates")
    op.drop_table("receivable_types")
    op.drop_table("currencies")
    op.drop_table("assignors")
    # ### end Alembic commands ###
